### ISSUE TITLE
Problems trying to run Jaydata 1.3.0 with webview android 2.3.4

### ISSUE THREAD

**Issue by davidjoan** [jaystack/jaydata#101]
The Problem is in the line 15596 
var xsltProcessor = new XSLTProcessor();

Android LogCat Message:
Uncaught ReferenceError: XSLTProcessor is not defined -- From line 15596 of http://ip-
server/js/lib/jaydata1.3/jaydata.js

this problem stop the loading.

I really appreciate any help

**Comment by agdolla** [comment]
There is no xslt on that device, use static schema. Generate the schema with jaysvcutil and include it into your app.

**Comment by davidjoan** [comment]
My app use a schema generated by jaysvcutil1.3.exe, but the problem is before that, is  when try to load jaydata.js, only in webview of android 2.3.4, because in android 4.1.2 works fine

**Comment by agdolla** [comment]
xslt is only used when we generate model from $metadata. Please paste some code here.

**Comment by robesz** [comment]
Hello @davidjoan ,
do you have any update on this issue?
please share your results!
Thanks,

**Comment by davidjoan** [comment]
Hello
@agdolla had the reason , the problem was when I tried to connect with the dynamic context like $data.initService('http://localhost:52999/todo') ..., jaydata try to generate a new file with entities, and android browsers can't process the xml used by jaydata, the solution was replace every dynamic context connection by a static schema connection, previously generated by me.

Thanks for the help

**Comment by robesz** [comment]
Great, thank you for your quick and detailed feedback!
