### ISSUE TITLE
$batch with content-length for odata4j

### ISSUE THREAD

**Issue by zendem** [jaystack/jaydata#104]
I'm using a odata4j Odata Service. This one needs content-length for $batch

Example what is send now by jaydata:
###### 

--batch_d53a-d88f-d96c
Content-Type: multipart/mixed; boundary=changeset_d87c-2350-864d

--changeset_d87c-2350-864d
Content-Type: application/http
Content-Transfer-Encoding: binary

MERGE Customer(1) HTTP/1.1
Content-Id: 1
MaxDataServiceVersion: 2.0
DataServiceVersion: 2.0
Accept: application/atomsvc+xml;q=0.8, application/json;odata=verbose;q=0.5, _/_;q=0.1
Content-Type: application/json;odata=verbose

{"LID":1,"City":"New York"}
--changeset_d87c-2350-864d
Content-Type: application/http
Content-Transfer-Encoding: binary

MERGE Order(1) HTTP/1.1
Content-Id: 2
MaxDataServiceVersion: 2.0
DataServiceVersion: 2.0
Accept: application/atomsvc+xml;q=0.8, application/json;odata=verbose;q=0.5, _/_;q=0.1
Content-Type: application/json;odata=verbose

{"LID":1,"Name":"Cookies"}
--changeset_d87c-2350-864d--

--batch_d53a-d88f-d96c--
###### 

This is what I need:
###### 

--batch_d53a-d88f-d96c
Content-Type: multipart/mixed; boundary=changeset_d87c-2350-864d

--changeset_d87c-2350-864d
Content-Type: application/http
Content-Transfer-Encoding: binary

MERGE Customer(1) HTTP/1.1
Content-Id: 1
MaxDataServiceVersion: 2.0
DataServiceVersion: 2.0
Accept: application/atomsvc+xml;q=0.8, application/json;odata=verbose;q=0.5, _/_;q=0.1
Content-Type: application/json;odata=verbose
Content-Length: Length of {"LID":1,"Name":"Cookies"}

{"LID":1,"City":"New York"}
--changeset_d87c-2350-864d
Content-Type: application/http
Content-Transfer-Encoding: binary

MERGE Order(1) HTTP/1.1
Content-Id: 2
MaxDataServiceVersion: 2.0
DataServiceVersion: 2.0
Accept: application/atomsvc+xml;q=0.8, application/json;odata=verbose;q=0.5, _/_;q=0.1
Content-Type: application/json;odata=verbose
Content-Length: Length of {"LID":1,"Name":"Cookies"}
{"LID":1,"Name":"Cookies"}
--changeset_d87c-2350-864d--

--batch_d53a-d88f-d96c--
###### 

Find no way how to write the important line bold. Hope you find the two lines with content-length :)

**Comment by robesz** [comment]
Note: contact David B. from Germany

**Comment by agdolla** [comment]
the same applied to .net, see here. http://stackoverflow.com/questions/15145656/how-to-show-content-length-for-batch-updates-in-c-sharp-for-odata-going-against
looks like odata4j has a fix for this problem: http://code.google.com/p/odata4j/issues/detail?id=245
but I can not see the fix attached to the ticket
sorry, we can not fix this
