### ISSUE TITLE
Kendo Initialization Script Tag closure missing

### ISSUE THREAD

**Issue by ghost** [jaystack/jaydata#107]
On the home page http://jaydata.org/ , in the "Understand JayData in 7 simple steps -
Step 1 - Initialize resources - KendoUI"

You are missing the closing ">" on the script declarations.  It should read:

```
<script src="http://cdn.kendostatic.com/2012.2.710/js/kendo.all.min.js"></script>
<script src="http://include.jaydata.org/jaydata.js"></script>
<script src="http://include.jaydata.org/jaydatamodules/kendo.js"></script>
```

**Comment by agdolla** [comment]
Hi
thanks for noticing, we'll fix it.

**Comment by robesz** [comment]
Thank you for your feedback, it was fixed with ther issues and typos. Please let me know if you discover any strange code there :) :+1:
