### ISSUE TITLE
Two EntitySets with the same EntityType wrong service document 

### ISSUE THREAD

**Issue by iguanaware** [jaystack/jaydata#109]
Todos1 and Todos2 have the same type.

$data.EntityContext.extend("TodoDatabase", {
        Todos2: { type: $data.EntitySet, elementType: Todo },
    Todos1: { type: $data.EntitySet, elementType: Todo }
});

Service Document only has one collection "Todos1", should have both.

Metadata seems ok and collections seem ok.

**Comment by agdolla** [comment]
Sorry, but this it not supported :( 
But if you create two subtypes Todo1 and Todo2 and both extend Todo then it should work.
