### ISSUE TITLE
.first() throws result count failed 

### ISSUE THREAD

**Issue by iguanaware** [jaystack/jaydata#114]
.first seems to be broken,  it should not throw the error.

"Single and first are very similar, only that single throws an exception if there’s more then one item matching the criterion or criteria."

The following collection has more than one item.  First throws the same exception as single.

context.StaticSensors.single(null,function (i) {console.dir(i);}); 

context.StaticSensors.first(null,null,function (i) {console.dir(i);});

{ name: 'Exception',
  message: 'result count failed',
  data: undefined }
{ name: 'Exception',
  message: 'result count failed',
  data: undefined }

ver 1.3.1

**Comment by shturec** [comment]
FYI
Works for me with oDataProvider and jaydata1.3.1

**Comment by robesz** [comment]
Hi @iguanaware ,
Could you please create a jsfiddle to reproduce the error? Which provider do you use?
Thanks, Rob

**Comment by iguanaware** [comment]
User Error.

Missing .onReady() in code and when I retested today it worked. 

Sorry,
Brian
