### ISSUE TITLE
OData: Loaded navigation properties are lost after attachOrGet on entity

### ISSUE THREAD

**Issue by shturec** [jaystack/jaydata#115]
It seems that after attaching an Entity for updates it looses the references to its navigation properties that have been loaded. My expectation was that the only change after attach is to provide it with context and set entity state.
In case this is by design, please advise how to retain the state properly after attachOrGet.

Consider the following example:
//load service entity with its properties (navigation property for Property entity types) inline
> ctx.Service.include('properties').filter('it.serviceId==1').toArray().done(function(s){service = s[0];})
Object {state: function, always: function, then: function, promise: function, pipe: function…}
XHR finished loading: "http://[host]:[port]/[app-context]/[odata-service]/Service?$expand=properties&$filter=(serviceId%20eq%201))". datajs-1.0.3.min.js:13

//list properties navigation property
> service.properties
[Property, Property, Property, Property]

//attach for updates
> service = ctx.Service.attachOrGet(service)
Service {initData: Object, context: AdventureEntities, _changedProperties: undefined, isValidated: false, _entityState: 10…}

//list properties navigation property
> service.properties
undefined

**Comment by robesz** [comment]
I think you should use attach() instead of attachOrGet() in this case. After changing the method, your code will behave like you expect.

**Comment by shturec** [comment]
Thanks. The funny thing is I can't reproduce it anymore and I was just about to close it. 
See the console log: 
> ctx.Service.include('properties').filter('it.serviceId==1').toArray().done(function(s){service = s[0];console.dir(s[0])})
    Object {state: function, always: function, then: function, promise: function, pipe: function…}
    XHR finished loading: "http://[host]:[port]/[app-context]/[odata-service]/Service?$expand=properties&$filter=(serviceId%20eq%201))". datajs-1.0.3.min.js:13
    Service
> service
Service {initData: Object, context: null, _changedProperties: undefined, isValidated: false, _entityState: undefined…}
> service.properties
[Property, Property, Property, Property]
>service = ctx.Service.attachOrGet(service)
Service {initData: Object, context: AdventureEntities, _changedProperties: undefined, isValidated: false, _entityState: 10…}
>service.properties
[Property, Property, Property, Property]

Is this still as expected?

**Comment by agdolla** [comment]
attachOrGet returns the object that you passed or another object that is already attached with that key. 

``` javascript
   ctx.MySet.include().first(function(o) {
       var z = ctx.MySet.attachOrGet(o);
   });
```

then the nav properties will be there, and you could simple call attach() instead of attachOrGet, but:

``` javascript
   ctx.MySet.include().first(function(o) {
       var x = new Type();
       x.id = o.id;
       ctx.MySet.attach(x);
       var z = ctx.MySet.attachOrGet(o);
   });
```

here z won't have the nav properties, as you get back x instead of o

hope it makes sense

**Comment by shturec** [comment]
I see. So probably in the first example I had attached an entity with the same id that did not have navigation properties beforehand. And then subsequently calling attachOrGet actually returned this very first object instead.
Thanks for the clarification!
