### ISSUE TITLE
Cannot read property 'DbCreationType' of undefined 

### ISSUE THREAD

**Issue by arjun141** [jaystack/jaydata#118]
I want to drop the websql table and create a new empty table but it is giving me 
![image](https://f.cloud.github.com/assets/5022903/886584/590e6cde-f9ec-11e2-9c4a-70b941b4e6d1.png)

**Comment by robesz** [comment]
Hello arjun,
You don't need the webSql in the namespace of the dbCreation mode. The correct one is $data.storageProviders.DbCreationType.DropAllExistingTables
