### ISSUE TITLE
Umlauts like ä ü in map with oData

### ISSUE THREAD

**Issue by CKiOne** [jaystack/jaydata#124]
Hi, we use umlauts in some Views over oData.
This dont work with JayData oData Provider and Internet Explorer 9+

thank you for all that work

**Comment by robesz** [comment]
Hello @ninichki ,
Does it work in different browser such as chrome? Could you please paste the model definition generated by jaysvcutil?
I would take a look.
Thanks,
Rob

UPDATE: please share the error message and request details (URL, body, headers, response) to describe what does not work.

**Comment by CKiOne** [comment]
It works in Chrome and Firefox

here is an example 

  $data.Entity.extend('allbudget_DEMOModel.BTC_30_01_01', {
     'KGR': { 'type':'Edm.Double' },
     'Abzüge_Zuschläge_Netto': { 'type':'Edm.Double' },
     'DIFF_AB_5': { 'type':'Edm.Double' },
     'Auftragswert_G2_Netto': { 'type':'Edm.Double' },
     'Rückstellung_Netto': { 'type':'Edm.Double' },
     'RISIKO_Netto': { 'type':'Edm.Double' },
     'PROGNOSE_N': { 'type':'Edm.Double' },
     'Prognose_Brutto': { 'type':'Edm.Double' },
     'FORD_N': { 'type':'Edm.Double' },
     'Zahlungsfreigaben_Netto': { 'type':'Edm.Double' },
     'Prognose_Freigabe_Netto': { 'type':'Edm.Double' },
     'Geleistet_Zahlung_Netto': { 'type':'Edm.Double' },
     'Freigabe_n_Skonto_Netto': { 'type':'Edm.Double','nullable':false,'required':true },
     'MANDNR': { 'type':'Edm.Int64' },
     'PROJEKT': { 'type':'Edm.String','maxLength':40 },
     'PROJEKTNR': { 'type':'Edm.Int64' },
     'Projekt_Suchname': { 'type':'Edm.String','maxLength':65 },
     'Projekt_Bauvorhaben': { 'type':'Edm.String','maxLength':76 },
     'PROJEKT_Anschrift': { 'type':'Edm.String','maxLength':113 },
     'DIN276_G1_Bezeichnung': { 'type':'Edm.String','maxLength':50 },
     'DIN_1_Summe': { 'type':'Edm.String','maxLength':50 },
     'ZWSUMME_DM': { 'type':'Edm.Double' },
     'KGR_Gruppe_1': { 'type':'Edm.Int64','nullable':false,'required':true },
     'DIN276_G3_Bezeichnung': { 'type':'Edm.String','maxLength':46 },
     'DIN276_Gruppe_1': { 'type':'Edm.Int32' },
     'DIN276_Gruppe_2': { 'type':'Edm.Int32' },
     'DIN276_G2_Bezeichnung': { 'type':'Edm.String','maxLength':50 },
  });

I think you need something like this: encodeURIComponent

 VisitProjectionExpression: function (expression, context) {
        ///<summary>

</summary>


        ///<param name="expression" type="$data.Expressions.ProjectionExpression" mayBeNull="false"></param>
        ///<param name="context" mayBeNull="false"></param>
        context.data = "";
        this.mapping = "";

```
    this.Visit(expression.selector, context);
    if (context['$select']) { context['$select'] += ','; } else { context['$select'] = ''; }
    context["$select"] += encodeURIComponent(context.data);
    context.data = "";
},
```
