### ISSUE TITLE
'length' method of SqLiteProvider returns wrong value when relations are included. 'skip' and 'take' are also affected.

### ISSUE THREAD

**Issue by marklagendijk** [jaystack/jaydata#125]
When the length() method is executed on a EntitySet which includes a relation, it returns the wrong length. 

Example: a Person can have 0 .. n Things.

``` javascript
context.saveChanges().then(function(){
  context.People
      .include('Things')
      .length(function(length){
        alert(length);   
      });
```

The above should return the number of People in the database. Instead it returns the sum of:
- The number of Things which are included.
- Plus the number of People which have 0 Things

[Here is a Plunker](http://plnkr.co/edit/2n670FD96g7roMJpogo8?p=preview) demonstrating the issue. Since it is an webSql issue you should open it in Chrome.

I suspect the bug which causes this also messes up paging (skip() and take()). I found out about this issue by trying to display a KendoUI Grid with a KendoDataSource of an item which included relations. The result was that the wrong amount of items where displayed on a page (eg 6 instead of 10) and a wrong total length was shown.

**Comment by robesz** [comment]
Hello @marklagendijk 
Thanks for the detailed description of the issue, it helped a lot to reproduce it! We will update the issue with our results!
Thank you!
Rob

**Comment by robesz** [comment]
The fix for this issue will be delivered in 1.3.2

**Comment by robesz** [comment]
The fix has been commited by @nochtap and will be released with the official 1.3.2 release. The issue can be solved with a nightly build.

**Comment by marklagendijk** [comment]
The original Plunker, [updated with the nightly build](http://plnkr.co/edit/BjePztLnMV9SM3wQfqBz?p=preview), shows that this issue has been fixed.

**Comment by robesz** [comment]
Awesome, thank you for the quick feedback!
