### ISSUE TITLE
is there webApi provider available in jaydata library, how can i download it?

### ISSUE THREAD

**Issue by walidward** [jaystack/jaydata#127]

**Comment by eliasgrenvald** [comment]
Sure, you don't need to download it, when you download JayData, it already exists on 'jaydataproviders' folder in the root.

**Comment by walidward** [comment]
thanx Mohsen for quick response, i tried to execute the example on jaydata blog (see the below link)

http://jaydata.org/blog/how-to-use-jaydata-with-asp.net-web-api---i

i want to see download that example and run it with visual studio but couldn't , is that availbale on github?

i'm trying  to use jaydata for CRUD operation with webApi, as single page application . appreciate your recommendation and help for providing me this example in the above link .

**Comment by eliasgrenvald** [comment]
No, as far as I know the sample is not available on Github, BTW it's pretty much straight forward and easy.
If you are in a hurry, you can start the implementation and let me know if you had any problem, unless I can provide you with a sample project by the next weekend. 
I wish I could help you right now but unfortunately I'm kind of busy this weekend.

**Comment by walidward** [comment]
Thanx Mohsen , its working now (was confused about the providers in the script folder, i thought that we have to build Web API provider from scratch like odataProvider ) , enjoy your weekend :)  , appreciate your help .

**Comment by DoubleExposure** [comment]
Guys, I am trying to use webapi with Jaydata. I am trying to load the serverside data clientside.
How can I do the following in Jaydata style instead of using angular's $http? Thanks
 $http.get('http://localhost:9810/api/program/getprograms/')
             .success(function (data) {
               $scope.programs = data;
               $scope.loading = false;

```
        data.forEach(function (data) {
            console.log(data.programID);
        });
    })           
 .error(function () {
     $scope.error = "An Error has occured while loading programs!";
     $scope.loading = false;
 });
```
