### ISSUE TITLE
$batch operations in oDataProvider / WebApiProvider don't include oDataServiceHost / apiUrl

### ISSUE THREAD

**Issue by SteRichardson** [jaystack/jaydata#131]
The $batch requestUri is set to the following:

oDataProvider.js: this.providerConfiguration.oDataServiceHost+"/$batch"
WebApiProvider.js: this.providerConfiguration.apiUrl+"/$batch"

But each individual request just uses the table name, e.g. batch requests to /odata/$batch will use /customers(1) instead of /odata/customers(1)

The requestUri for each individual request will need updating to include the base URL.

**Comment by agdolla** [comment]
Hi
in the request we send customers(1) and not /customers(1) so we send relative uri which should be ok

**Comment by SteRichardson** [comment]
I would have expected that also, but it did not seem to be the case when I tried it earlier, I had an error stating that the /customers(1) URL could not be found. I'd be interested to see if anyone else has this error, if I have time I'll see if I can reproduce and put an example together.

**Comment by SteRichardson** [comment]
It looks as though this may be to do with how ASP.NET Web API OData interprets the request, it seems to combine the request with the URL host root, rather than the data service host root.

Not a problem for you guys!
