### ISSUE TITLE
Bug found on SqLiteProvider.js: No "AND" added in "ON" clauses when there are multiple keys.

### ISSUE THREAD

**Issue by homer-jay** [jaystack/jaydata#132]
I've found a bug in the SQLite provider. I can confirm this bug exists in versions 1.3 and 1.3.1.

The problem is in this fragment of code, starting in line 1243:

```
if (setIndex > 0) {
    sqlBuilder.addText(" ON (");
    var toSet = this.infos[setIndex];
    var toPrefix = "T" + toSet.AliasNumber;
    var fromSetName = toSet.NavigationPath.substring(0, toSet.NavigationPath.lastIndexOf('.'));
    var temp = this.infos.filter(function (inf) { return inf.NavigationPath == fromSetName; }, this);
    var fromPrefix = "T0";
    if (temp.length > 0) {
        fromPrefix = "T" + temp[0].AliasNumber;
    }
    toSet.Association.associationInfo.ReferentialConstraint.forEach(function (constrain, index) {
        sqlBuilder.addText(fromPrefix + "." + constrain[toSet.Association.associationInfo.From]);
        sqlBuilder.addText(" = ");
        sqlBuilder.addText(toPrefix + "." + constrain[toSet.Association.associationInfo.To]);
    }, this);
    sqlBuilder.addText(")");
}
```

This is the code that builds the clause for the "ON" part. So if there's a children entity and the primary key in the parent table is just 1 column, it builds a string like this:

SELECT <columns> FROM <CHILDREN_TABLE> T0 LEFT OUTER JOIN <PARENT_TABLE> T1 ON (T0.parent__parentPK = T1.parentPK) 

The problem is that when the parent key is a compound key (2 or more columns are marked as key), the produced string are like this:

SELECT <columns> FROM <CHILDREN_TABLE> T0 LEFT OUTER JOIN <PARENT_TABLE> T1 ON (T0.parent__parentPK1 = T1.parentPK1T0.parent__parentPK2 = T1.parentPK2) 

That of course fails since it has not placed the " AND " separator between the two conditions. Here's how the ON clause should look like:

ON (T0.parent__parentPK1 = T1.parentPK1 AND T0.parent__parentPK2 = T1.parentPK2) 

And here's my proposal for the fix, starting in the loop at line 1253:

```
toSet.Association.associationInfo.ReferentialConstraint.forEach(function (constrain, index) {
    if(index > 0){
         sqlBuilder.addText(" AND ");
    }
    sqlBuilder.addText(fromPrefix + "." + constrain[toSet.Association.associationInfo.From]);
    sqlBuilder.addText(" = ");
    sqlBuilder.addText(toPrefix + "." + constrain[toSet.Association.associationInfo.To]);
}, this);
```

**Comment by agdolla** [comment]
Thanks, we'll look into it

**Comment by agdolla** [comment]
Thanks for reporting the problem and also for sending us the solution! This fix will be included in the next release due next week.
