### ISSUE TITLE
JayDataContext entity sets should have read method

### ISSUE THREAD

**Issue by oocx** [jaystack/jaydata#138]
An EntitySet in a JayDataContext should have a read method, so that I can query for a single item by primary key.

I can use $data("My.CustomEntity").read(key). However, I would prefer if this method was available in a typed way in the context generated by JaySvcUtil. I could then simply use someting like container.CustomEntity.read(key) and have full intellisense for TypeScript.

**Comment by agdolla** [comment]
in the latest release (1.3.2) we have a new method called find which does that
we haven't much time to document it so the only documentation existing now is in the release notes: http://jaydata.org/blog/release-notes
it works for odata right now
