### ISSUE TITLE
IE11 XSLTProcessor issue

### ISSUE THREAD

**Issue by RainerAtSpirit** [jaystack/jaydata#142]
Using jaydata with ie11 fails with a XSLTProcessor() undefined error. According to this http://msdn.microsoft.com/en-us/library/ff955298(v=vs.85).aspx ActiveXObject can't any longer be detected in a conditional statement, but it's still available.

Updating `_processResults` from

   `if (window.ActiveXObject) {`

to something along the line 

   `if (window.ActiveXObject || window.ActiveXObject !== undefined) {`

seems to fix that issue... at least in IE11

Here's a ticket from jQuery that provides some more background info http://bugs.jquery.com/ticket/14475

**Comment by robesz** [comment]
Hi Rainer,

Thanks for the advice! We will address this issue in the next version of the library. Not sure if we include this fix or refactor this subsystem to work without XSLTProcessor.

**Comment by RainerAtSpirit** [comment]
Looking forward to your solution

**Comment by manojnaik47** [comment]
Thanks for your solution.

**Comment by robesz** [comment]
This fix has been released with JayData 1.3.5 - thanks @RainerAtSpirit

**Comment by RainerAtSpirit** [comment]
@robesz Confirmed, thanks!
