### ISSUE TITLE
Model Definition Issue/Query

### ISSUE THREAD

**Issue by jamesnogra** [jaystack/jaydata#144]
Hello, how can I add a custom field for a property in defining models?
Like:

$data.Entity.extend("Offices", {
    Id: { type: "id", key: true, computed: true },
    OfficeName: { type: "string", maxLength:50, alternateName:"OfficeNameX" }
});

In this case, I have added an alternateName custom field but when I open the /$metadata URL, I cannot see anywhere the alternateName:"OfficeNameX", just the type and maxLength. Is there a way to add one or more custom fields?

**Comment by agdolla** [comment]
Start the name of the property with $ sign
