### ISSUE TITLE
odata-server using incorrect IDs for foreign keys

### ISSUE THREAD

**Issue by pauljoey** [jaystack/jaydata#146]
I'm trying to get a oData server working with an existing mongo back-end using the odata-server npm package v1.3.1. We have a schema that looks like this:

```
$data.Entity.extend("app.family", {
    id: { type: "id", key: true, computed: true },
    name: { type:  "string" },
    children:   { computed: true, type: "Array", 
                  elementType: "app.child", inverseProperty: "family" }
});

$data.Entity.extend("app.child", {
  "id": { type: "id", key: true, computed: true },
  "name":  {"type": "string" },
  "firstName": {"type": "string" },
  "family":    { "title": "Family", type: "app.family", 
                  inverseProperty: "children" },
});

```

The "family" property in the database contains the string of the ID of the parent family - I've tried storing both the ObjectId.toString() and the base64 representation used by odata-server.  

However, when querying a child with $expand=family, the family property has the same data (ID and name) as the parent child object.

**Comment by robesz** [comment]
Hi @pauljoey ,

This happens because JayData uses internal fields to manage the relationships, but you don't have these fields in your existing MongoDB. You can examine the required schema by saving an entity to a different collection to find out the document schema you have to migrate your existing data if you want to use relationships.

**Comment by pauljoey** [comment]
I must have been going by an old article that mentioned that "foreign keys" were be stored as strings. Here's a sample script for others wanting to convert a field containing an ObjectId into a odata-server formatted reference.

I used this successfully after converting my sqlite3 database using **mongify**. Haven't tested extensively, but foreign key references and back references appear to return the correct data.

``` bash

#!/bin/bash

DATABASE=$1
TABLE=$2
FIELD=$3
TARGET=$4

usage ()
{
  echo "usage: $0 <database> <collection> <field> <target>"
  echo "database: mongo database containing the collection"
  echo "collection: collection/table containing the foreign key"
  echo "field: the field in collection containing the foreign"
  echo "         ObjectId reference"
  echo "target: target collection referenced by the the field"
}

if [ ! "$DATABASE" ]; then
  echo "Missing table"
  echo
  usage
  exit 1
fi

if [ ! "$TABLE" ]; then
  echo "Missing table"
  echo
  usage
  exit 1
fi

if [ ! "$FIELD" ]; then
  echo "Missing field"
  echo
  usage
  exit 1
fi

if [ ! "$TARGET" ]; then
  echo "Missing target entity type"
  echo
  usage
  exit 1
fi

mongo --eval "conn = new Mongo();
db = conn.getDB('$DATABASE');

db.$TABLE.find().forEach(
  function(i) {
    if (i.$FIELD && i.$FIELD instanceof ObjectId) {
      var field = i.$FIELD;
      i.$FIELD = {
        '\$ref': '$TARGET',
        '\$id': field
      };
      i.${FIELD}__id = field;
      db.$TABLE.save(i);
    }
  }
)
"
```
