### ISSUE TITLE
Odata concurrency support?

### ISSUE THREAD

**Issue by RainerAtSpirit** [jaystack/jaydata#16]
Odata is supporting optimistic concurrency control.

http://www.odata.org/documentation/operations#ConcurrencycontrolandETags

Is that something that is support OOTB with JayData?

**Comment by PeterAronZentai** [comment]
Yes and No.
JayData at this point supports optimistic concurrency with a timestamp field coming from the Entity definition (EntityFramework approach).
The good news is that the infrastructure in JayData is ready for handling entity ETag values as per documentation. We try to push the support into 1.0.6 (next week). Thanks again for helping us continuously.

**Comment by RainerAtSpirit** [comment]
It's a pleasure. I like what I see so far in JayData and just checking for known hazards when dealing with OData. That will ease my life whenever I'm ready to use your product in an upcoming project ;-).
I'll leave this question open for the time being.

**Comment by robesz** [comment]
The optimistic concurrency support with ETag has been released yesterday with JayData 1.1.0, the blogpost is on the way :)

**Comment by RainerAtSpirit** [comment]
Excellent! Looking forward to get hands on.

Rainer
