### ISSUE TITLE
Method Tunneling through POST?

### ISSUE THREAD

**Issue by RainerAtSpirit** [jaystack/jaydata#17]
Here's another question in regards to OData.

http://www.odata.org/documentation/operations#MethodTunnelingthroughPOST

Does JayData support Method tunneling OOTB?

**Comment by PeterAronZentai** [comment]
This one is a yes:) JayData uses Microsoft's datajs 1.0.3 for write operations to be as standards compliant as possible. This post shows how to configure datajs transport to use POST tunneling: http://datajs.codeplex.com/wikipage?title=Frequently%20Asked%20Questions

**Comment by RainerAtSpirit** [comment]
Excellent! Thanks for the pointer.

**Comment by PeterAronZentai** [comment]
No about tunneling but you mind find this approach interesting as a way of sharing use cases
http://jsfiddle.net/JayData/mc3x4/

I remember you mentioned SharePoint  OData does not support JSONP?
Any info on wheather SharePoint supports access-control-allow  headers that would make CORS available?

**Comment by RainerAtSpirit** [comment]
No CORS, no JSONP, no anonymous access. SharePoint REST requires that you're already authenticated. Of course there's no straight forward way to do this remotely as it depends on the authentication method you're using. 

For Claims there's a good article at http://allthatjs.com/2012/03/28/remote-authentication-in-sharepoint-online/ but our demo server runs in classic mode and we can't switch.

Haven't looked into it, but Lightswitch V11 has the ability to access SP listdata.svc and then republish as a new OData service. So that might be an option. 

Later the year SharePoint 15 beta might bring something new in, but up til that jsfiddle unfortunately won't work with SharePoint listdata.svc.

**Comment by RainerAtSpirit** [comment]
BTW: For this fiddle it might be better to uncheck `Normalizee CSS` to make the result clearer, but I agree with you that this is a great way to play around and exchange JayData code.

http://jsfiddle.net/jnPNR/

**Comment by PeterAronZentai** [comment]
yup... did it and looks much better so updated the base. thanks :)

**Comment by PeterAronZentai** [comment]
Yeah, LightSwitch can do that and for CORS, its quite easy to deploy settings with LightSwitch server side to allow cross origin access.
In fact I am preparing a blog backed by an authenticating LightSwitch server side. LightSwitch kicks ass in terms of easiness of actually defining an odata endpoint with authorization, quueris and backend service aggregation.

**Comment by RainerAtSpirit** [comment]
Recently there've been some rumors on the lightswitch team blog like http://blogs.msdn.com/b/lightswitch/archive/2012/03/13/using-lightswitch-odata-services-in-a-windows-8-metro-style-application-elizabeth-maher.aspx, but a blog about a cross browser html5 app talking to an Lightswitch Odata service wouldn't be too bad :). Looking forward to it.
