### ISSUE TITLE
jaydata with odata provider and odatacontroller issue

### ISSUE THREAD

**Issue by elhaddad1** [jaystack/jaydata#179]
issue : when using multi service in system so i need to request many metadata and this operation make a big issue with performance.
# any idea about performance to be better.

**Comment by robesz** [comment]
Hello @elhaddad1 ,

I assume you use dynamic context by calling $data.initService(). In this case the performance can be improved by pre-generating the client-side data model using in development time using JaySvcUtil.exe.
