### ISSUE TITLE
Known Issue: $data.Class.define must throw error when base type is undefined

### ISSUE THREAD

**Issue by nochtap** [jaystack/jaydata#2]
This code is faulty, it has $data.Entity instead of $data.types.Entity. However it still runs without error or any indication of a problem.

``` javascript
$data.Class.define("$org.Types.Department", $data.Entity, null, {
Id: { dataType: "int", key: true, computed: true },
Name: { dataType: "string" },
Address: { dataType: "string" },
Employee: { dataType: "Array", elementType: "$org.Types.Employee", navigationProperty: "Department" }
}, null);
```

**Comment by jaydata** [comment]
There is a workaround still the fix arrives: use the type.extend function instead of the low level $data.Class.define. This will throw an error if type does not exists. 
Example:
$data.x.Entity.extend("Product") would throw an error while $data.Entity.extend would run as expected.
