### ISSUE TITLE
$select within $expand doesn't seem to work

### ISSUE THREAD

**Issue by plusplusben** [jaystack/jaydata#204]
I'm a bit new to JayData and OData, but I requested this url on my odata server...

http://host/service/Todo/Todos?$expand=Creator($select=FirstName)

but I'm getting this error back from my server..

[Error: Syntax error at line 0, char 8. Expected: right parenthesis: ')'. Source:Creator(>>>>$<<<<select=FirstName). Caller: parseMemberPath]

Is this kind of query supported with JayData?  Here's the spec that I'm following...

"Properties of related entities can be specified by including the $select query option within the $expand.
Example 33:

http://host/service/Products?$expand=Category($select=Name)"

**Comment by Malyngo** [comment]
I don't know that spec, if I had to make such a request, I'd use this one:
http://host/service/Products?$expand=Category&$select=*,Category/Name
Tested with an Web Api OData backend.

Using Jaydata, I only know this way::
context.Products.include("Category").map("{Name: it.Name, Category:{Name: it.Category.Name}}").toArray()
unfortunatly, you will have to put every property of the Product into the map parameter, as far as I know.

**Comment by plusplusben** [comment]
Yeah, I think I found my error.  I'm looking at the spec for 4.0, but I think the server I'm using is not 4.0.  I'll close this issue.  Thanks for the help.  Your way works correctly for me.
