### ISSUE TITLE
incompatibility with node v0.12

### ISSUE THREAD

**Issue by kildem** [jaystack/jaydata#205]
JaySvcUtil.js requre node_xslt (line 278),
but node_xslt doesn’t compile with the last version of node (v0.12),
is it possible to use other module rather than
 node_xslt?

**Comment by jaydata** [comment]
Do you need the server or the client capabilities?

**Comment by kildem** [comment]
server capabilities

**Comment by jaydata** [comment]
That can operate without node_xsl - till we fix it try faking the node_xsl module - its functionality is not required for a server  to run/operate.

**Comment by kildem** [comment]
if I replace node_xslt with xslt4node it works in node v0.12 too

```
var xslt4node = require('xslt4node');
      var config = {
        xslt: transformXslt,
        source: metadata,
        result: String,
        params: {
          'SerivceUri': cnf.SerivceUri,
           'EntityBaseClass': cnf.EntityBaseClass ,
           'ContextBaseClass': cnf.ContextBaseClass ,
           'AutoCreateContext': cnf.AutoCreateContext ,
           'ContextInstanceName': cnf.ContextInstanceName ,
           'EntitySetBaseClass': cnf.EntitySetBaseClass ,
           'CollectionBaseClass': cnf.CollectionBaseClass ,
           'DefaultNamespace': cnf.DefaultNamespace ,
           'MaxDataserviceVersion': (versionInfo.maxVersion || '3.0') ,
           'AllowedTypesList': cnf.typeFilter ,
           'GenerateNavigationProperties': cnf.navigation 
       }
      };
     return xslt4node.transformSync(config);
```

**Comment by kildem** [comment]
xslt4node is the only xslt transform I found that doesn't have incopatibility with previous versions and the last version of node v0.12

**Comment by kildem** [comment]
node_xslt installation fails in Node v >= 0.11.13 https://github.com/bsuh/node_xslt/issues/24.
What do you think about my pull request to fix this problem? https://github.com/jaydata/jaydata/pull/207
