### ISSUE TITLE
OData provider - filtering by Guid is not working with OData v4

### ISSUE THREAD

**Issue by Malyngo** [jaystack/jaydata#211]
In the alpha version of Jaydata (1.4-alpha), filtering by Guid is not working when using OData v4.

The query Jaydata is building looks like this:

```
/odata/Customer?$filter=(Id eq guid'e1805121-3c3a-47e1-bf86-fc71f09f18d1')
```

but should look like this:

```
/odata/Customer?$filter=(Id eq e1805121-3c3a-47e1-bf86-fc71f09f18d1)
```

**Comment by PeterAronZentai** [comment]
This is how can you modify it to comply with the standard - that apparently has been modified  in the meantime.

``` JavaScript```
$data.oDataConverter.escape['$data.Guid'] = function(v) { return v; }
```

**Comment by robesz** [comment]
This will be resolved in the next release - Nov-Dec
