### ISSUE TITLE
[odata-server] Problem with newsreader example

### ISSUE THREAD

**Issue by englertm** [jaystack/jaydata#216]
Hello,

I've installed the odata-server: <code>npm install odata-server</code>

When I start the example "newsreader.js": <code>node newsreader.js</code>

I receive this errors:
<code>
D:\web\node_modules\odata-server\node_modules\mongodb\lib\server.js:274
      process.nextTick(function() { throw err; })
                                          ^
TypeError: undefined is not a function
    at D:\web\node_modules\odata-server\node_modules\jaydata\lib\Types\StoragePr
oviders\mongoDB\mongoDBStorageProvider.js:80:32
    at Array.forEach (native)
    at fn (D:\web\node_modules\odata-server\node_modules\jaydata\lib\Types\Stora
geProviders\mongoDB\mongoDBStorageProvider.js:78:22)
    at D:\web\node_modules\odata-server\node_modules\jaydata\lib\Types\StoragePr
oviders\mongoDB\mongoDBStorageProvider.js:139:19
    at D:\web\node_modules\odata-server\node_modules\mongodb\lib\db.js:206:5
    at connectHandler (D:\web\node_modules\odata-server\node_modules\mongodb\lib
\server.js:272:7)
    at g (events.js:199:16)
    at emit (events.js:107:17)
    at D:\web\node_modules\odata-server\node_modules\mongodb\node_modules\mongod
b-core\lib\topologies\server.js:388:23
    at D:\web\node_modules\odata-server\node_modules\mongodb\node_modules\mongod
b-core\lib\topologies\server.js:795:13
</code>

Can you tell me what's wrong? Do I have to change the example coding or do I have to do something in my mongoDB?

Thanks in advance!
Marcus

**Comment by lazarv** [comment]
Hello Marcus,

the node.js MongoDB driver version >=2.x is not supported by the JayData MongoDB provider. Please use MongoDB version 1.4.38. Use `npm install mongodb@1` to install.
