### ISSUE TITLE
Updating an OData Entity with String Key

### ISSUE THREAD

**Issue by jasper07** [jaystack/jaydata#22]
When I try to update an entity whose key property is type Edm.String I get an bad request error.

The service is expecting

http://services.odata.org/Northwind/Northwind.svc/Customers('ALFKI')

instead the code is creating the request URI as 

http://services.odata.org/Northwind/Northwind.svc/Customers(ALFKI)
the quotes are missing

getEntityKeysValue:
..
keyValue = entity.data[field.name];
                if (field.dataType == "string")
                    keyValue = "'" + keyValue + "'";
                result.push(field.name + "=" + keyValue);
            }
should be 
 if (field.dataType == "Edm.String" || ...)

Cheers
John  P

**Comment by robesz** [comment]
Hi John, 
thank you for the detailed report. 
The fix of this issue will be released right in the news version (1.1.1). 
Thanks,
Robert

**Comment by jaydata** [comment]
It has been fixed already. You can get the fix by  gitcloning the dev branch (the default) of JayData and manually building.
