### ISSUE TITLE
Is JayData dead?

### ISSUE THREAD

**Issue by ludydoo** [jaystack/jaydata#228]
Hi,

I was just wondering what is happening with this project? There isn't many commits, and last posts on social media from JayData are from 2014.

**Comment by PeterAronZentai** [comment]
Nope - just things slowed down massively in the past year on the new feature development part. We focus on JayData customer support and consultancy.

We are in the signing process of a SeriesA investment in the range of $2m - hopefully we will have this go public by W1 October. The investment is to reinvigorate product development that is just overwhelmed now with paid customer support.

**Comment by robesz** [comment]
The new release is scheduled for the end of November, beginning of December
