### ISSUE TITLE
find() throws an error when no entry is found

### ISSUE THREAD

**Issue by Malyngo** [jaystack/jaydata#241]
When I use find with a key that is not in the database, the returned promise fails.

I would expect it to succeed and just return a null value.
Or is this indeed how it is supposed to be?

**Comment by Malyngo** [comment]
hm, well, a change here in the API of Jaydata would possible break stuff in some applications that are using it.
But maybe you could at least remove the console.error when this happens?

**Comment by PeterAronZentai** [comment]
No, this is by design - and is modeled after .NET EF similar functionality. Find expects exactly one result - the entity with that id. if you happen to read for an entity with its id, that is not in the database, that is 95% of the time is an error.

**Comment by Malyngo** [comment]
Ok, thanks, so it is just my assumption that is not correct :)

**Comment by Malyngo** [comment]
I just used the EF DBSet.Find(object key) method, and if it doesn't find anything, it just returns null.
So the EF method does behave like I previously expected.
