### ISSUE TITLE
jaydatamodules/kendo.js - observable.set("property", null) is throwing an error

### ISSUE THREAD

**Issue by Malyngo** [jaystack/jaydata#242]
When trying to set a property to null or undefined, kendo.js will throw an error.

This is because it is testing on the propValue if innerInstance is available [(Line 244 in kendo.js).](https://github.com/jaystack/jaydata/blob/development/src/JayDataModules/kendo.js#L244)
`propValue = propValue.innerInstance ? propValue.innerInstance() : propValue;`
will result in an NullReference error.

This is easily fixed by changing the above line to:
`propValue = propValue && propValue.innerInstance ? propValue.innerInstance() : propValue;`

If you like, I can create a quick PR for that.

**Comment by PeterAronZentai** [comment]
Sorry for late response. We would be delighted - if it is still actual.

**Comment by Malyngo** [comment]
Hi @PeterAronZentai, I have added a PR for this.
