### ISSUE TITLE
A query on an entity with a complex property that an enum throws an exception

### ISSUE THREAD

**Issue by Lyonis** [jaystack/jaydata#243]
Hi,

When I try to perform a query to retrieve an entity with a complex property with an enum, the following error is raised: "Cannot create instance from enum type!" on line 13787 in jaydata.js file.

My context was created dynamically via a $metadata OData v4.

I identified the problem on line 19512 : 

`context.src + = 'var' + + item = new (Container.resolveByIndex ('+ indexType +')) (); ';`

This code must create a new type without regard to the type enum.

So I changed the code pending correction:

```
var isEnum = resolvedType.isAssignableTo && resolvedType.isAssignableTo(_index2.default.Enum);
if (isEnum) {
    context.src += 'var ' + item + ' = Container.resolveByIndex(' + typeIndex + ')[di["' + context.current + '"]];';
}
else {
    context.src += 'var ' + item + ' = new (Container.resolveByIndex(' + typeIndex + '))();';
}
```

Best regards

**Comment by PeterAronZentai** [comment]
Could you please tell what JayData version were you using? Enum support for complex end entity types were only added in 1.5ctps.

**Comment by Lyonis** [comment]
Yes, it's in jaydata 1.5ctp
Le 4 avr. 2016 5:47 AM, Peter Aron Zentai notifications@github.com a écrit :Could you please tell what JayData version were you using? Enum support for complex end entity types were only added in 1.5ctps.
