### ISSUE TITLE
JayData Pro D.TS file does not compile

### ISSUE THREAD

**Issue by ChristopherPope** [jaystack/jaydata#258]
Our project currently uses JayData NON pro and we want to upgrade to the pro version. I went to your website and downloaded a trial copy of the pro version which contained a D.TS file.

The Pro version D.TS file has several problems in it when I compile using TS 1.5. For example:

All boolean types are named bool which is invalid in TS

All array types are named Array without the generic type argument which causes the TS compiler to bark.

Queryable.map() does not have all available signatures. According to your docs, Queryable.map() has 2 signatures but only one is available in the Pro D.TS file

**Comment by robesz** [comment]
Hi,
The next stable Pro version will be available after the stable open-source version. I recommend to use the RC version of the latest open-source lib, so you will have a smoother upgrade to once it is shipped.
