### ISSUE TITLE
SP2013 OAuth support?

### ISSUE THREAD

**Issue by RainerAtSpirit** [jaystack/jaydata#27]
Are there plans for native support ?

http://msdn.microsoft.com/en-us/library/office/apps/fp179897(v=office.15)#SP15_dataaccessoptions_connectivity

**Comment by PeterAronZentai** [comment]
We will look into this. Some kind of OAuth support will be provided for JayStorm (the cloud based JayData store). If it is possible we should align it with SP2013 OAuth support.
The good news is that yesterday we presented JayData to a representative of the OData / WCF team @ Microsoft. They liked what we show and we will get support in making JayData even better.

**Comment by RainerAtSpirit** [comment]
Sounds like good news. Make sure to get MS marketing people on board, that's where the money is [VBEG](http://www.all-acronyms.com/VBEG).

**Comment by PeterAronZentai** [comment]
I do hope we can get to that level, yes. Frankly, the server side odata/jaydata + nodejs is super interesting. In fact OData could be the basis to give some structure to AJAX and to get rid-of 80% of $.ajax() and JSON.parse codes as FunctionImport + MetaData seems pretty enough to formulate arbitrary method oriented APIs.

**Comment by RainerAtSpirit** [comment]
Be assured I'll give it a try when it becomes available ;-).
