### ISSUE TITLE
1.5.6 Update

### ISSUE THREAD

**Issue by bstaley** [jaystack/jaydata#270]
@robesz I hate to be this person, but can we get a status update on 1.5.6? Looks like #256 was fixed on August 8th and the rest of the sprint seems like documentation updates. The last update on this sprint was about 21 days ago. I could really use #257 but I prefer to get the official release from the team. Any update would be appreciated. Thanks.

**Comment by robesz** [comment]
Hi @bstaley ,

JayData 1.5.6 was already released, you can read the release notes here - http://jaydata.org/blog/release-notes
The download link is available here - http://jaydata.org/download

**Comment by bstaley** [comment]
@robesz Ah, sorry about that. I was watching [this](https://github.com/jaystack/jaydata/milestone/18) milestone. Thanks for the reply.
