### ISSUE TITLE
1.1.1 and debugging of odata provider?

### ISSUE THREAD

**Issue by RainerAtSpirit** [jaystack/jaydata#30]
With 1.1.1  I see it's loaded and working, but I'm unable to get a hold on it in Firebug or Chrome as it won't show up in the script list. Am I missing something?

Thanks

**Comment by PeterAronZentai** [comment]
This might come from the automatic loading of the provider files based on usage. To overcome this you should simply include the oData provider in the html page right after the script reference to jaydata but before the context definition. This way it will appear in the scripts list as expected.
Thank you for bearing with 1.1.1 issues :)

**Comment by RainerAtSpirit** [comment]
Using `RequireJS` anyways, so at the end I decided to wrap the `jaysvtutil` output in a `define` block and add jaydata and the oDataProvider as dependency. 
1. That solved the debugging issue as the odataprovider now shows up again in Firebug and Chrome
2. I no longer run into situtations where the provider wasn't loaded yet by jaydata

``` javascript
define(['jaydata', 'JayData1.1.1/jaydataproviders/oDataProvider.min'], function () {

var app = window.app || {};

        ////////////////////////////////////////////////////////////////////////////////////////
        ////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
        //////                             oData v1                                    /////////
        ////////////////////////////////////////////////////////////////////////////////////////

        (function(global, $data, undefined) {

...
          })(window, $data);

});
```
