### ISSUE TITLE
Jaydata.org website hacked / malicious redirect

### ISSUE THREAD

**Issue by Konbonix** [jaystack/jaydata#301]
As of 2018-11-15 when visiting JayData.org the user's browser is redirected to a blogspam site. Redirects appear to rotate to different sites. It appears load the normal jaydata.org landing page for a split second before the redirect initiates. 

Posting here as I wasn't sure how else to contact the maintainer.

**Comment by Konbonix** [comment]
Looks like this was resolved a few hours after I posted the issue.

**Comment by robesz** [comment]
Hello @Konbonix ,
Thank you for letting us know, we do appreciate it.
The site is fixed now and runs smoothly again
