### ISSUE TITLE
1.1.1 orderBy raises error

### ISSUE THREAD

**Issue by RainerAtSpirit** [jaystack/jaydata#33]
This is working

``` javascript
   postbox.subscribe("selectedList", function (newValue) {
            if (newValue !== '') {
                app.context[newValue]
                    .include(include)
                    .map(chooseMap(newValue))
                    .take(take)
                    .toArray(allItems);
            }
        });
```

As soon as I add `orderBy()` or `orderByDescending()` the system raises an error

```
Global parameter Modified not found. For query parameters use 'this.field' notation
```

Same error occurs if I shorten the expression:

``` javascript
  app.context[newValue]
                   .orderBy('Modified')
                   .toArray(allItems);
```

**Comment by lazarv** [comment]
If you order by a string expression, you have to use it like 'it.Modified'. You missed the entity lambda part of the expression. Or you can use a function as the order expression. Like .orderBy(function(it){ return it.Modified; })

**Comment by RainerAtSpirit** [comment]
Thanks for the quick feedback.

I got it working using your recommendation to use an order expression.

``` javascript
 postbox.subscribe("selectedList", function (newValue) {
            if (newValue !== '') {
                app.context[newValue]
                    .orderByDescending(function(newValue){ return newValue.Modified; })
                    .include(include)
                    .map(chooseMap(newValue))
                    .take(take)
                    .toArray(allItems);
            }
```

Construction the lambda part like `.orderByDescending("'" + newValue + ".Modified'")` works as well, but feels a little bit clumsy.

I was following the example at http://jaydata.org/blog/javascript-language-query-jslq-101#h3_26
where I got the impression that a simple fieldname could be used as well.

``` javascript
<script>
    northwind.Products.orderBy("ProductName")
        .forEach(function(product) { console.log(product) });
</script
```
