### ISSUE TITLE
JaySvcUtil fails to generate context definition to Bing service

### ISSUE THREAD

**Issue by robesz** [jaystack/jaydata#35]
The developer tried to use JaySvcUtil to generate context definition of the following Bing service:
https://api.datamarket.azure.com/Bing/SearchWeb/$metadata

The tool fails with error message.

The problem is caused by the possibility of a secondary XML namespace of OData v2.
http://msdn.microsoft.com/en-us/library/microsoft.data.edm.library.edmconstants(v=vs.103).aspx

JaySvcUtil should recognize http://schemas.microsoft.com/ado/2009/08/edm as a OData v2 service.

**Comment by jaydata** [comment]
Fixed by @borzav : https://github.com/jaydata/JaySvcUtil/commit/8fe55ac15de9e9de3b08944d8937f5b0509c1661#commitcomment-1651426

**Comment by PeterAronZentai** [comment]
I have not seen OData v2.1 namespaces to be included in the current JaySvcUtil.js or exe

**Comment by robesz** [comment]
The tool has been re-released with the namespace support -  the latest version can be fount at https://jaysvcutil.codeplex.com
