### ISSUE TITLE
Support simple field name notation in .orderby and in .select/.map

### ISSUE THREAD

**Issue by PeterAronZentai** [jaystack/jaydata#36]
It would be nice to support

``` javascript
myContext.mySet.orderBy("FieldName") 
```

``` javascript
myContext.mySet.map("FieldName") 
```

This should be a convenience method that in the background builds up a memberExpression as expected downwards.

The specs to decide if the predicate is a fieldNameOnlyNotation is as follows:
if predicate is string and it does not contain "it." and also does not contain a space then it should be treated as a field name of the respective entity type. The function implementation should append a "return it." prefix and fallback to the existing logic.

**Comment by PeterAronZentai** [comment]
It is partially done! queryable now supports .order( scolumn ) with only a string column name. if the name starts with an - the ordering will be reversed. simple but effective for those grid sorting usecases.

**Comment by RainerAtSpirit** [comment]
Good news. Just to confirm that will be in 1.2?

**Comment by PeterAronZentai** [comment]
Sure thing.... :)

**Comment by PeterAronZentai** [comment]
This case is solved: for orderBy/orderByDescending you can you queryable.order("Column") or queryable.order("-Column")
