### ISSUE TITLE
Support for PATCH instead of MERGE in Odata 3.0

### ISSUE THREAD

**Issue by RainerAtSpirit** [jaystack/jaydata#37]
At OData it states

http://www.odata.org/blog/2012/5/11/odata-v3-demo-services

> You can send PATCH requests instead of MERGE. The behavior is identical otherwise.

but in the preliminary SharePoint 2013 docs it states

http://msdn.microsoft.com/en-us/library/fp142386(v=office.15).aspx

> Although the SharePoint REST service supports MERGE requests for backward compatibility reasons, we recommend you use PATCH requests instead.

Are you going to support this?

**Comment by PeterAronZentai** [comment]
This we have to check with WCF Data Services, if tests go green there is no reason not to send PATCH instead of MERGE.

**Comment by robesz** [comment]
It seems that PATCH will be the default when using OData v3 endpoints. Will be released with v1.3 very soon

**Comment by RainerAtSpirit** [comment]
Thanks for the heads up. Now we only have to wait till MS implements _api/$metadata in the RTM SharePoint bits.
