### ISSUE TITLE
In Cordova dynamic provider loading can not work

### ISSUE THREAD

**Issue by PeterAronZentai** [jaystack/jaydata#40]
In Cordova we can not load scripts with XMLHttpRequest as there is no underlying webserver to address. For this reason if a provider is about to be dynamic loaded and also we are in Cordova/Titanium environment the user should be warned with a dialog box, that requests the manual reference of the provider js file into the application html.

**Comment by robesz** [comment]
This bug is fixed since 1.2.3 since the automatic provider loading doesn't use XMLHttpRequest, but appends a <script> tag to the DOM.
