### ISSUE TITLE
OData provider - Filter by GUID field should be supported

### ISSUE THREAD

**Issue by robesz** [jaystack/jaydata#41]
Filtering by GUID field should be compiled to $filter=Id eq guid'fda07801-e125-44c9-95be-0001c9407585'

The guid prefix is missing right now, which causes Error 400 on the server.

Reference: http://www.odata.org/developers/protocols/overview

The bug can be easily reproduced using the Netflix example:

Netflix.context.TitleAwards
  .filter(function(ta) { return ta.Id == 'fda07801-e125-44c9-95be-0001c9407585'} )
  .toArray(function (t) {console.dir(t);})

**Comment by PeterAronZentai** [comment]
This is now supported as of V1.2. The syntax is:
filter( function(it) { return it.Id == $data.parseGuid('your-guid-as-string'); })
