### ISSUE TITLE
Use POST/DELETE methods if only 1 object has changed

### ISSUE THREAD

**Issue by PeterAronZentai** [jaystack/jaydata#42]
This is due to tomorrow.

**Comment by PeterAronZentai** [comment]
It is done, checked in and is made available for download on codeplex (http://jaydata.codeplex.com/releases/view/93252) as v1.1.2.b

Please note, that restfull calls are only done if one and only one object is changed. In v 1.2 we release additional support for RESTfull calls for multiple objects changed scenarios.

**Comment by oising** [comment]
Hey Peter - do you guys also put this builds on NuGet?

**Comment by PeterAronZentai** [comment]
Nope, 1.1.2b was only for some real burning cases.. Next NuGet package will be deployed with 1.2 on 10th the Sept. I do hope we'll wont fsck up with it now :)
