### ISSUE TITLE
Single throws exception or not call cb

### ISSUE THREAD

**Issue by jaydata** [jaystack/jaydata#43]
``` javascript
this.filter("it." + key.name + " == this.value", { value: keyValue }).single(null, cb);
```

does not call cb

``` javascript
this.filter("it." + key.name + " == this.value", { value: keyValue }).single(cb);
```

throws
jaygrid.js:137
Grid model created jaygrid.js:174
template registered:Edm.String jaygrid.js:137
template registered:Edm.Boolean jaygrid.js:137
Grid model created jaygrid.js:174
VisitCall: Only fields can have operations: CallExpression jaydata.js:77
DefaultError: DEFAULT ERROR CALLBACK!

Exception
 jaydata.js:75
Uncaught DefaultError: DEFAULT ERROR CALLBACK! jaydata.js:79

**Comment by PeterAronZentai** [comment]
syntax for the single is set.single( predicate, params, cb)
