### ISSUE TITLE
SqLite provider - include() functionality seems to be broken

### ISSUE THREAD

**Issue by Micha4711** [jaystack/jaydata#44]
Using include() in a query in combination with the SqLite data provider throws an exception:

line: 1139
message: "Can't find variable: projectionBuilder"
sourceId: 1954108352
sourceURL: "http://somehost/jaydata/jaydataproviders/SqLiteProvider.js"

Please visit http://jaydata.org/forum/viewtopic.php?f=3&t=91 for more information on this issue.

I verified this issue using the latest github sources, so it's still existing.

**Comment by PeterAronZentai** [comment]
The error comes from a routine that was incompletely updated when we changed to v2 of the ModelBinder. Chances are that it'll be fixed prior to releasing 1.2

**Comment by robesz** [comment]
The support for include() in SQLite provider has been delivered in JayData 1.2.2 - http://jaydata.org/blog/release-notes
