### ISSUE TITLE
NuGet 1.1.1 build cannot load oDataProvider

### ISSUE THREAD

**Issue by oising** [jaystack/jaydata#46]
The NuGet package build (1.1.1) doesn't work. It tries to load the oDataProvider.js from /jaydataproviders/ instead of /Scripts/jayadataproviders/ which is where the package places it. Not sure how that got past the testers.

**Comment by PeterAronZentai** [comment]
Thanks :) I checked, and tests use the standalone version.  Fix will come with 1.2

**Comment by oising** [comment]
Okely dokely. Thanks. Is the fix checked into the trunk now?
