### ISSUE TITLE
Neither tests.html, tests_JayData.html nor tests_JayData_min.html is working?

### ISSUE THREAD

**Issue by oising** [jaystack/jaydata#48]
I've gotten the latest (as of today) from the development branch, mounted it in IIS express and tried loading the qunit test harness pages in Chrome. Nothing works - they all error out and fail to even load correctly. How do I run the tests to verify development builds? Are these the right files? If not, consider clearing out the junk :)

**Comment by oising** [comment]
hmm, so I figured out I think I need to put this through a build with gnu make. Sigh. It would be nice if you could include a Makefile.win or msbuild equivalent so I didn't need to install a ton of one-time use only gnu tools on my windows box.

**Comment by PeterAronZentai** [comment]
I'll check on this, but yes, a make all is required before tests could run. As of now if have 16 failing tests out of 1680.
Please also consider that on windows tests will start wcf data services endpoints backed by SQL CE 4.0. 
Sorry but I am not that much experienced with make on Windowsbut I do know that half of the team works on Windows and they somehow do build. Lemme check on them and gather some info to you regarding how to build on Windows.

Some secret info to you: your download also contains JayData based OData SERVER with MongoDB or SqLite as backend (i prefer Mongo) plus dynamic JaySvcUtil.js that renders JaySvcUtil.exe an unnecessary burden. Docs to be created with 1.2 in the premises.

**Comment by robesz** [comment]
As the tests are working fine, the issue can be closed. Windows build can be proposed as a feature request.
