### ISSUE TITLE
Bug in Odata tutorial 

### ISSUE THREAD

**Issue by caxelrud** [jaystack/jaydata#52]
In the tutorial "How to build a Simple OData-based ajax application" I am getting the following message when trying to run the html:
"Line: 20
"Error: Unable to get property 'toArray' of undefined or null reference"

It related to the 2nd line of the existing code:
        $(function () {
            nwcontext.Categories.toArray(function (categories) {
                categories.forEach(function (category) {
                    $('#categories').append(
                        createItemLI(category.Category_Name, category.Category_ID, 'category'));
                });
            });
        });

**Comment by caxelrud** [comment]
Just to give more information. The problem exists following the walkthroughs: How to build a Simple OData-based ajax application.
But, the similar example from:
"Documentation, Examples, Download examples, JayData Northwind Demo"
works fine expect that uses old version of the library.
So, I am looking for an working example with the current version on odata. Thanks.

**Comment by PeterAronZentai** [comment]
Hello, one possible reason is that from v 1.1.1 providers are not included in the core stack, they are automatically loaded upon first use. This makes a call to onReady mandatory

``` javascript
nwcontext.onReady(  function() { 
  // context is ready here! 
});
```

You can eliminate this JIT loading by manually including the odataprovider.js in the html page.
Separating the providers from the core seems was a bad decision that we might just reconsider.

**Comment by RainerAtSpirit** [comment]
Separating the providers from core was a good decission. What you might want to reconsider it the way loading is implemented. My favorite -as proposed before- would be AMD. Same is true for JayDataModules.
As this would be a breaking change this needs to be go into a 2.X version with proper documentation and examples ;-).

**Comment by PeterAronZentai** [comment]
Yeah, v2 is coming - ETA is xmas with all the OData V3 support. Now with a 6 months experience with jaydata 1.x we pretty much see what is cool and what could be done better. BTW I do appreciate the V3 features each day more and more - we are so eager to have them supported both on the client and the server. For example: supporting stateful server code with the actual state kept on the client (and marshaled using the  OData 'call convention') is a huge thing. Napa client apps with a smart server side support can actually make a difference.

**Comment by caxelrud** [comment]
I tried the suggestion of using 'nwcontext.onReady' and I got another error:
Line: 15019
Error: Unable to get property 'oData' of undefined or null reference

Here is the source:
<!DOCTYPE html>
<html>

<head>
    <script type="text/javascript" src="/scripts/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="/scripts/JayData.js"></script>
    <script type="text/javascript" src="northwind.js"></script>

```
<title></title>
<script>
        // context is ready here! 
        jQuery.support.cors = true;
        var nwcontext = new northwind.NorthwindEntities({
            name: 'oData',
            oDataServiceHost: 'http://services.odata.org/Northwind/Northwind.svc'
        });
        $(document).ready(function () {
            nwcontext.onReady(function () {
                nwcontext.Products.toArray(function (products) {
                console.dir(products);
        });
    });
    });
```

   </script>
</head>

<body>
</body>
</html>

**Comment by PeterAronZentai** [comment]
It still seems a module load error... in the mean time, the docs do not work without some modifications - due to the drop of jQuery ajax from 1.1.0, and changing to datajs for protocol layer. The required extra line is 

``` javascript
OData.defaultHttpClient.enableJsonpCallback = true;
```

Here is what I did that yielded the expected results...
-Created Emtpty Web Project with Visual Studio 2012
- Installed JayData nuget package with Install-Package JayData
- Created northwind context js with JaySvcUtil.exe 
- Opened the newly generated nwcontext.js and grabbed the last lines (context creation) and moved to the html page into a script block.
- Manually added jaydatamodules/odataprovider.js to the page.

So my working example looks like this

``` html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <script src="Scripts/jquery-1.7.2.js"></script>
    <script src="Scripts/jaydata.js"></script>
    <script src="Scripts/jaydataproviders/oDataProvider.js"></script>
    <script src="nwcontext.js"></script>
    <script>
        OData.defaultHttpClient.enableJsonpCallback = true;
        //this is cut/pasted from nwcontext.js
        var context = new ODataWeb.Northwind.Model.NorthwindEntities({
            name: 'oData',
            oDataServiceHost: 'http://services.odata.org/Northwind/Northwind.svc'
        });

        //this is required since jsonp requires document.body to be ready
        $(function () {
            context.Categories.toArray(function (items) {
                console.dir(items);
            });
            context.Products.toArray(function (items) {
                console.dir(items);
            });
        });
    </script>
    <title></title>
</head>
<body>

</body>
</html>
```

**Comment by PeterAronZentai** [comment]
Could you help finding the error in the walkthrough? Are you referring to: http://jaydata.org/tutorials/how-to-build-a-simple-odata-based-ajax-application ? It looks like what you are pointing to, but it uses a local WCF service and not the northwind online demo, and I was not able to locate the one that is using cross origin requests.

UPDATE: I think I found, it was the codeplex.com/jaydata intro page. Thank you for finding this docs bug.

**Comment by teyc** [comment]
There's a missing reference to datajs. The following works for me:

```
<script src="Scripts/jquery-1.7.2.js" type="text/javascript"></script>
<script src="Scripts/datajs-1.0.3.js" type="text/javascript"></script>
<script src="Scripts/jaydata.js" type="text/javascript"></script>
<script src="Scripts/jaydataproviders/oDataProvider.js" type="text/javascript"></script>
<script src="northwind.js" type="text/javascript"></script>
```

**Comment by PeterAronZentai** [comment]
Yeah this is also valid... We also removed datajs from the library so that you have to inlude/dowload it separately...

**Comment by robesz** [comment]
Hey @teyc ,

I hope the include fixed your app - according to our experience it should work, but please provide me feedback if I can close the issue or ask for further help.

**Comment by teyc** [comment]
Yes it has. Please update tutorial.

**Comment by robesz** [comment]
Thank you for your feedback, the tutorial and the codeplex page have been updated.
