### ISSUE TITLE
JayData 1.2.2 issue with SharePoint listdata.svc

### ISSUE THREAD

**Issue by RainerAtSpirit** [jaystack/jaydata#55]
This simple query produces an `value not convertable to $data.Integer: TypeError:` in version 1.2.2

``` javascript
ctx.Tasks.toArray(function (tasks) {
    console.dir(tasks);
});
```

The issue occurs at the `Owshidden field. While it's returned correctly as an integer in jaydata.js line 14345 this will be converted: 

``` javascript
 this.result = converter.call(this.rawDataList, this.modelBinderConfig);
```

this.modelBinderConfig.$item.Owshiddenversion overwrites the integer with the __metadata etag value, which in SharePoint looks like `"W/"1""`, clearly not an int.

**Comment by RainerAtSpirit** [comment]
Here is a link to the gist, with the $metadata and .js and d.ts files produced by JayServiceUtil 

https://gist.github.com/3972900

**Comment by robesz** [comment]
Moved to JayData 1.2.4 with high priority

**Comment by robesz** [comment]
Hello  @RainerAtSpirit,
Could you please confirm if this can be closed.
Thank you

**Comment by RainerAtSpirit** [comment]
@robesz Tested with 1.2.6 and it's working correctly.

**Comment by robesz** [comment]
excellent, thank you for your feedback!
