### ISSUE TITLE
Auto-loading LocalStore provider

### ISSUE THREAD

**Issue by robesz** [jaystack/jaydata#56]
Initializing LocalStore provider works only by referencing the InMemoryPrivider.js

$todo.context = new $todo.Types.ToDoContext({ name: 'LocalStore', databaseName: 'todo' });

The page generates JavaScript error if I miss loading the provider:

Failed to load resource: the server responded with a status of 404 (Not Found) -  /jaydataproviders/LocalStoreProvider.min.js

Uncaught TypeError: Cannot read property 'LocalStore' of undefined -  jaydata.min.js:470

**Comment by PeterAronZentai** [comment]
Mitigate this by including /jaydataproviders/inmemoryprovider.js in the htmlpage
Fix is on the way.

**Comment by robesz** [comment]
This fix has been released in JayData 1.2.3
