### ISSUE TITLE
Navigation property question in case of loadItemProperty

### ISSUE THREAD

**Issue by robesz** [jaystack/jaydata#63]
This is a question posed by @rameshUSC in https://github.com/jaydata/jaydata/issues/60

As that question was lost in the long thread, I create a separate issue to find out if this is scenario is supported or not.

Hi Viktor,

I tried to use loadItemProperty from context object  as below and I seeing
the navigation property values from this " $('#clientPH').append(citem" .

 But, it does not attached to client1 (parent) object . can you check
below code and let me know?

I am using  this line - console.dir(client1) to check the whether
navigation property is loaded to client1 or  not. I am seeing still a null
value for alternate_name nav property. Did I miss anything? Thx for your
help.

   context.onReady(function () {

```
            var clients = context.client;
            clients.toArray(function (items) {
                    console.dir(items);
                });

            clients.forEach(function (client1) {
                            //for display item:
                    var item = $('<li>'); item.text("Client ID: " +
```

client1.client_id);

```
                    var lp = context.loadItemProperty(client1,
```

'alternate_name', function (presult) {

```
                        //display the client entity details
                        $('#clientPH').append(item);

                        presult.forEach(function (an) {

                            var citem = $('<ul>'); citem.text(
```

"Alternate Name( " + an.client_id + "): " + an.last_name);
                                //display the client's related entity
details- in this case alternate_name details
                                $('#clientPH').append(citem);
                            });

```
                    });


                     console.dir(client1);
                });

            });
```

Thanks,

**Comment by borzav** [comment]
Hello Ramesh,

loadItemProperty just retrieves the not loaded properties. So you have to write it back to the original entity if you want to see on that.
Btw, if you want to set an 'alternate_name' property and then see that on console, you need to do this inside an async callback.

Viktor

**Comment by robesz** [comment]
Thank you for your help Viktor! 
@rameshUSC, does this answer your question? Viktor explained me, that loadItemProperty is designed to implement lazy-load scenarios. To retrieve the related object, you have get in a second query.

**Comment by rameshUSC** [comment]
I have also tried like below and it did not work. I wanted to see alternate_name navigation property from client1 entity.  var lp = context.loadItemProperty(client1, 'alternate_name', function (presult) {

```
                        //display the client entity details
                        $('#clientPH').append(item);


                        presult.forEach(function (an) {
                            // alert('inner:' + client.client_id);
                            var citem = $('<ul>'); citem.text("Alternate Name( " + an.client_id + "): " + an.last_name + ' ' + an.first_name);
                            //display the client's related entity details- in this case alternate_name details
                            $('#clientPH').append(citem);

                        });
                        console.log(client1);
                    });
```
