### ISSUE TITLE
oDataProvider $data.Date fieldConverter is expecting a string to convert, but receiving a Date

### ISSUE THREAD

**Issue by oising** [jaystack/jaydata#64]
Versions:
- jaydata 1.2.5.1 (from nuget)
- datajs 1.1.0  (from nuget)

My endpoint is a simple odata v3 endpoint. I receive this follow error from oDataProvider.js (line 583 according to chrome)

> Uncaught TypeError: Object Tue Dec 11 2012 14:35:34 GMT-0500 (Eastern Standard Time) has no method 'substr' 

which is coming from here:

``` javascript
   fieldConverter: {
        value: {
            fromDb: {
                 ...
                '$data.Date': function (dbData) { return dbData ? new Date(parseInt(dbData.substr(6))) : undefined; },
```

which appears to be problematic because at this point, dbData is _already_ a native Date object, not a string. Perhaps this has something to do with datajs?

Btw, I am aware of the recent checkin concerning the return of `undefined` - it should really be returning `dbData`

**Comment by RainerAtSpirit** [comment]
OData v2 returns date in a different format than v3. As v3 is not fully supported by JayData monkey patching seems to be the only option right now. See https://github.com/jaydata/jaydata/issues/31

**Comment by oising** [comment]
Thanks - already monkey patched.
