### ISSUE TITLE
TypeError: context.Categories is undefined  var categories = context.Categories.toArray();

### ISSUE THREAD

**Issue by xxxccc** [jaystack/jaydata#65]
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <script src="Scripts/datajs-1.0.3.js" type="text/javascript"></script>
    <script src="Scripts/jquery-1.8.3.js" type="text/javascript"></script>
  
      <script src="Scripts/jaydata.js" type="text/javascript"></script>
       <script src="Scripts/Ecom.js" type="text/javascript"></script>
    <title></title>
</head>
<body>
 <h1>Categories</h1>
    <ul id="categories"></ul>
    <h1>Products</h1>
    <ul id="products"></ul>
</body>
</html>

<script>
//    jQuery.support.cors = true;
    context = new demo.EcomEntities({ name: 'oData', oDataServiceHost: 'http://localhost:2351/DemoService.svc' });
    $(document).ready(function () {
        var categories = context.Categories.toArray();
        $.when(categories).then(function (categories) {
            categories.forEach(function (category) {
                var item = $('<li>'); item.text(category.Category_Name);
                $('#categories').append(item);
            });
        });
    });
</script>

**Comment by agdolla** [comment]
You have to use onReady() before you can use the context, something like this:
    $(document).ready(function () {
      context.onReady(function() {
      })
    })
or
  $(document).ready(function () {
     context.onReady()
     .then(function() {
     })
  })

or your can include oDataProvider manually and then you don't need onReady()

**Comment by PeterAronZentai** [comment]
It is as Gabor wrote. To have a simple promise pattern to wait for both the document and the context could be written like thi:

``` javascript
var context = new YourContextClass({ name: 'oData', oDataServiceHost: 'your svc url' });
$.when($.ready, context.onReady()).then(function () {
    alert($('#pager').length + context.Categories);
});
```
