### ISSUE TITLE
.include and second level navigation properties on sqLite/webSQL

### ISSUE THREAD

**Issue by oising** [jaystack/jaydata#67]
So, I have the following entity relationships:

-Parent
--Child
---Grandchild

Which, when I want to query from `oDataProvider`, I can write:

```
var q = db.Parent
    .include("Child")
    .include("Child.Grandchild")
    .forEach( ... )
```

This gets translated into:

```
/service.svc/Parent?$expand=Child,Child/Grandchild
```

Which is great. However, when I have this data cached in sqLiteprovider, only `.include("Child")` is recognized. The second level `.include("Child.Grandchild")` is not recognized as syntactically valid by the parser.

original discussion here: http://jaydata.org/forum/viewtopic.php?f=3&t=130&p=528&sid=3d1718369eb2847f1c11103eeb17aebe#p528

The relationship exists in SQLite, so it should be handled as expected. One of the best features of jaydata is the _mostly_ equivalent behavior of providers. With the two most flexible providers, I would expect near parity for JQL.

**Comment by PeterAronZentai** [comment]
This will get covered in all client providers by 1.3

**Comment by robesz** [comment]
This feature has been released, deep include is available in SQLite Provider

**Comment by oising** [comment]
Good job, guys.

**Comment by Alexious-sh** [comment]
Still doesn't work for me in JayData 1.3.6. It returns an error: "Unknown expression type to handle: EntitySetExpression" if any second-level include present.
