### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by benreynwar** [jaystack/jaydata#7]
When running make I appear to be missing the following files from the repository:

Types/RowConverter.js
Types/StorageProviders/SqLite/ModelBinder/sqLiteModelBinderCompiler.js
Types/StorageProviders/SqLite/ModelBinder/sqLiteEFModelBinderCompiler.js
Types/StorageProviders/SqLite/ModelBinder/sqLiteOLModelBinderCompiler.js
Types/StorageProviders/oData/ModelBinder/oDataModelBinderCompiler.js
Types/StorageProviders/oData/ModelBinder/oDataEFModelBinderCompiler.js
Types/StorageProviders/oData/ModelBinder/oDataOLModelBinderCompiler.js
Tools/compiler.jar

**Comment by nochtap** [comment]
Hi,

I fixed this bug in development branch with #b8ba225 checkin.
I hope, this version works perfectly.

nochtap
