### ISSUE TITLE
Include failed when pointing to entity with multiple key fields

### ISSUE THREAD

**Issue by sebastieno** [jaystack/jaydata#76]
Hello all,

I'm starting using JayData with SqlLite Provider and I'm facing an include problem.
My entities look like :

$data.Entity.extend("FoodRation", {
    Id: { type: "int", key: true, computed: false },
    WorkshopId: { type: "int", key: true, required: true },
    RationId: { type: "int", required: true },
    Ration: { type: "Ration", inverseProperty: "FoodRations" }
});

$data.Entity.extend("Ration", {
    Id: { type: "int", key: true, computed: false },
    WorkshopId: { type: "int", key: true, required: true },
    FoodRations: { type: "Array", elementType: "FoodRation", inverseProperty: "Ration" }
});

My entities key are always set to the Id and WorkshopId fields.
I need to get all rations, including the linked food rations. So I use the following request : context.Rations.include("FoodRations").toArray([...]).

The generated sql request looks like :
SELECT [...] FROM Rations T0 LEFT OUTER JOIN FoodRations T1 ON (T0.Id = T1.Ration__IdT0.WorkshopId = T1.Ration__WorkshopId) 

The LEFT OUTER JOIN condition is not well generated.

Do you know a workaround ? Is that a by design limitation ?

Thanks for your help.

**Comment by PeterAronZentai** [comment]
Hey Sebastieno,

This looks to be an issue in JayData, caused by the composite primary key. This we shall fix shortly.
In the meantime can you fall back on using simple, one-field keys in the entities?

**Comment by sebastieno** [comment]
Thanks a lot for your quick response.
I prefer to not use a one field key.
Do you already have a quick fix that I can manually integrate into the provider javascript code ? I am very short in the delay and I unfortunately cannot wait for your fix.
If not, I think I will add a column in my entities corresponding to the concatenation of the multiple keys fields, or maybe generate a Guid.

Again, thanks a lot.

**Comment by PeterAronZentai** [comment]
You have the foreign key fields manually enlisted on FoodRations. You might expect the system to join the tables based on these key fields. Please be aware, that JayData will generate foregin key fields automatically, the workshop__id and ration__id fields will be created nevertheless - at the moment you are not able to hint key field usage in JayData. 

You can however enlist the foreign key fields with the exact names JayData would generate (Ration__Id and Ration__WorkshopId).

**Comment by PeterAronZentai** [comment]
Both concatenation and Guid could work... See online/offline example for how to work with Guids in jaydata. http://jaydata.org/blog/how-to-create-a-synchronized-online-offline-data-application-with-javascript-and-jaydata

Be aware that multiple keys scenarios has less unit test coverage then simple solo key cases so the encounter with a bummer has more chance...

**Comment by sebastieno** [comment]
Ok. I will use the concatenation method.
Thanks a lot.
