### ISSUE TITLE
MaxODataServiceVersion should be 3.0 instead of 2.0

### ISSUE THREAD

**Issue by hongyes** [jaystack/jaydata#83]
When sending a simple get request to feed, the request payload doesn't work with web api odata. The Accept header accepts atomsvc+xml which doesn't work in feed; json fullmetadata which is supported in v3 json light but because MaxDataServiceVersion is 2.0,  it doesn't work neither; application/json, in web api odata, only json light formatter supports this content type. So none of the content type works for a this basic scenario.

Please se MaxDataServiceVersion to 3.0 to support json light on client. Here is the request sent from JayData.

GET /Products HTTP/1.1
Host: localhost:50231
Connection: keep-alive
Accept: application/atomsvc+xml;q=0.8, application/json;odata=fullmetadata;q=0.7, application/json;q=0.5, _/_;q=0.1
MaxDataServiceVersion: 2.0
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.57 Safari/537.17
Referer: http://localhost:50231/odataservice/ODataTestClient.html?testNumber=9
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3

**Comment by robesz** [comment]
Hello Hongyes,

Thanks for your feedback, we are still working on OData v3 support, which will be released in very soon with JayData 1.3.

I will update this issue to notify you about the release.

**Comment by robesz** [comment]
Hi @hongyes ,

This can be customized while creating the context.

var context = new MyContext({name: 'oData', maxDataServiceVersion: '3.0',...........});
