### ISSUE TITLE
OData multiple deep include bug

### ISSUE THREAD

**Issue by jpattersonz** [jaystack/jaydata#88]
reference : https://github.com/jaydata/jaydata/issues/12

There is still a bug in deep includes.  After you deep include a path, all other includes will fail.  There is a workaround if you only need to deep include 1 path, where you just move that deep include to the bottom of your list of includes.  However if you must deep include multiple paths (like me!), everything after the first deep include will return as undefined.  If you look at the datajs result, all of the properties are there.  The model binder is not being built correctly.  From my debugging, I believe this issue resides in the $data.modelBinder.ModelBinderConfigCompiler.DefaultSelection method.

examples:

---

northwind.Employees.include("Orders.Customer").include("Territories.Region")

in this case Orders.Customer will expand correctly, and Territories (and thus Region) will be undefined.

---

northwind.Employees.include("Territories.Region").include("Orders.Customer")

in this case Territories.Region will expand correctly, and Orders (and thus Customer) will be undefined.

---

This is a big deal for me and I'm hoping I've provided enough information to help you resolve the issue quickly.  I have a full visual studio example zip file I can send if you need it.  Let me know.

Thanks,

Jeff

**Comment by robesz** [comment]
Hi Jeff,

Thank you for the precisely detailed report, we take a look into it and get back to you.

Bye,
Robert

**Comment by robesz** [comment]
The issue has been fixed by @borzav in the DEV branch.

**Comment by jpattersonz** [comment]
Is there a way for me to get the development branches build output without having to build it myself?

Jeff

**Comment by PeterAronZentai** [comment]
Sorry, nope. GitHub does not have such a feature unfortunately. You can build it with cygwin, or better yet: we can build you a version any time you ask, as part of the service (until the nightly build service of ours goes online). This can be done during business ours GMT. Tomorrow your jira account will be activated and we can upload this ondemand build with the fix there. Is this a way your are content with?

**Comment by jpattersonz** [comment]
That’s fine.  Thanks.

Jeff

**Comment by agdolla** [comment]
you can download it from here:
https://jaydata-build.s3.amazonaws.com/jaydata-20130308092712.zip

**Comment by jpattersonz** [comment]
Thanks, it works!  So can I expect this fix to make it into the 1.2.8 release?

**Comment by robesz** [comment]
Excellent, thank you for your quick feedback. 
Sure, the fix will be included in the next official release coming soon (v1.3)

**Comment by robesz** [comment]
Hi @jpattersonz ,
We released an official bugfix release (v1.2.7.1), which is available at http://jaydata.org/download
You can update the library in your project with the fixed version.

Bye,
Robert
